CREATE TABLE [USERS] (
	[UID] uniqueidentifier PRIMARY KEY,
	FirstName varchar(50),
	LastName varchar(50),
	Email varchar(100),
	Phone varchar(16),
	Adress varchar(255),
	AuthorisationLevel int,
	Salt varbinary(MAX),
	HashedPassword varbinary(MAX),
	IsActivated int
)
CREATE TABLE [PRODUCTS] (
	[ID] uniqueidentifier PRIMARY KEY NOT NULL,
	Brand varchar(50) NOT NULL,
	Model varchar(100) NOT NULL,
	Price float NOT NULL,
	Stock int NOT NULL,
	ReleaseYear int NOT NULL,
	[Type] int NOT NULL,
	[Image] varbinary(MAX),
	MbMemoryType int,
	MbRamSlots int,
	MbM2Slots int,
	MbSata3Slots int,
	MbIsWifiCapable bit,
	CpuCores int,
	CpuClockSpeed float,
	CpuSocket varchar(50),
	CpuThreads int,
	RamSticks int,
	RamMemory int,
	RamMemorySpeed int,
	RamInternal int,
	RamMemoryType int,
	RamPins int,
	GpuClockSpeed int,
	GpuDisplayPorts int,
	GpuVideoRam int,
	GpuFans int,
	GpuBusType int,
	GpuSize int,
	PsuOutput int,
	PsuModular bit,
	PsuCertificate varchar(100),
	CaseFormFactor int,
	CaseExpansionSlots int,
	CaseFans int,
	CaseDriveBays int,
	CaseGpuSize int
)